### PR TITLE
FIx the build of reicastsa

### PR DESCRIPTION
**Pull request by magicseb**
Note : It will generate a working reicast build but we need to fix more 

- add dreamcast system in es_system.cfg 
- default controller mapping .cfg
- bios localisation (actually we had to create .local/share/reicast/data folder in storage

### CODE REVIEW

**Comment by magicseb** [comment]
- you need also to modify .config/reicast/emu.cfg to set default mapping and set the first controller...

**Comment by magicseb** [comment]
and yes... it's fully working emu :D

**Comment by shantigilbert** [comment]
Thank you, I will test this and merge the PR!

**Comment by shantigilbert** [comment]
I am getting

```
 from core/rend/gles/gltex.cpp:1:
core/libretro-common/include/glsym/rglgen_headers.h:64:19: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
                   ^
compilation terminated.
```
 

did you change anything to the package.mk ?

**Comment by shantigilbert** [comment]
@magicseb do you have a working exampe of the .cfg files? I already addedd to ES but I can't seem to find a working example of the .cfg files.

**Pull request merged**
