### PR TITLE
Update genesis plus gx makefile for ARM

### PR DESCRIPTION
**Pull request by zach-morris**
See https://github.com/libretro/Lakka-LibreELEC/issues/203

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thank you, if this fix is on the libretro git I will merge it when I do an update. (I am on vacation right now)

**Comment by zach-morris** [comment]
Cool, hopefully you weren't effected by the quake!

**Comment by shantigilbert** [comment]
Thanks for the concern! Fortunately I am not near to where it hit.

**Comment by shantigilbert** [comment]
I merged this, although you are using the old branch, the new branch is Sx05RE_8.2

**Pull request merged**
